/*

		SFX_enemy_death

		Sound Effect File.
		
		Info:
			Length			:	7
			Priority		:	10
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_enemy_death_h_INCLUDE
#define __SFX_enemy_death_h_INCLUDE
#define CBTFX_PLAY_SFX_enemy_death CBTFX_init(&SFX_enemy_death[0])
extern const unsigned char SFX_enemy_death[];
#endif