/*

		SFX_12

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	1
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_12_h_INCLUDE
#define __SFX_12_h_INCLUDE
#define CBTFX_PLAY_SFX_12 CBTFX_init(&SFX_12[0])
extern const unsigned char SFX_12[];
#endif