/*

		SFX_player_death

		Sound Effect File.
		
		Info:
			Length			:	31
			Priority		:	15
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_player_death_h_INCLUDE
#define __SFX_player_death_h_INCLUDE
#define CBTFX_PLAY_SFX_player_death CBTFX_init(&SFX_player_death[0])
extern const unsigned char SFX_player_death[];
#endif