/*

		SFX_press_start

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	15
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_press_start_h_INCLUDE
#define __SFX_press_start_h_INCLUDE
#define CBTFX_PLAY_SFX_press_start CBTFX_init(&SFX_press_start[0])
extern const unsigned char SFX_press_start[];
#endif