/*

		SFX_enemy_hit

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_enemy_hit[] = {
48, // Header
3,
1, 136, 13, 96, 1, 136, 8, 112, 1, 136, 4, 113
};