/*

		SFX_enemy_hit

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_enemy_hit_h_INCLUDE
#define __SFX_enemy_hit_h_INCLUDE
#define CBTFX_PLAY_SFX_enemy_hit CBTFX_init(&SFX_enemy_hit[0])
extern const unsigned char SFX_enemy_hit[];
#endif