/*

		SFX_player_fire

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	1
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_player_fire_h_INCLUDE
#define __SFX_player_fire_h_INCLUDE
#define CBTFX_PLAY_SFX_player_fire CBTFX_init(&SFX_player_fire[0])
extern const unsigned char SFX_player_fire[];
#endif