/*

		SFX_enemy_fire

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_enemy_fire[] = {
192, // Header
3,
0, 34, 128, 240, 131, 135, 0, 34, 128, 160, 45, 135, 0, 34, 128, 128, 6, 135
};