/*

		SFX_enemy_hit

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_enemy_hit", ROM0
_SFX_enemy_hit::
db $30; 48	'0'
db $03; 3
db $01; 1
db $88; 136
db $0d; 13
db $60; 96
db $01; 1
db $88; 136
db $08; 8
db $70; 112	'p'
db $01; 1
db $88; 136
db $04; 4
db $71; 113	'q'