/*

		SFX_enemy_death_special

		Sound Effect File.
		
		Info:
			Length			:	14
			Priority		:	14
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_enemy_death_special_h_INCLUDE
#define __SFX_enemy_death_special_h_INCLUDE
#define CBTFX_PLAY_SFX_enemy_death_special CBTFX_init(&SFX_enemy_death_special[0])
extern const unsigned char SFX_enemy_death_special[];
#endif