/*

		SFX_enemy_death_special

		Sound Effect File.
		
		Info:
			Length			:	14
			Priority		:	14
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_enemy_death_special", ROM0
_SFX_enemy_death_special::
db $fe; 254
db $0e; 14
db $00; 0
db $aa; 170
db $80; 128
db $fe; 254
db $06; 6
db $87; 135
db $a0; 160
db $00; 0
db $2a; 42
db $80; 128
db $ee; 238
db $06; 6
db $87; 135
db $40; 64
db $00; 0
db $aa; 170
db $80; 128
db $d7; 215
db $06; 6
db $87; 135
db $70; 112	'p'
db $03; 3
db $a2; 162
db $80; 128
db $c4; 196
db $2d; 45
db $87; 135
db $51; 81	'Q'
db $04; 4
db $aa; 170
db $80; 128
db $b3; 179
db $59; 89	'Y'
db $87; 135
db $52; 82	'R'
db $03; 3
db $2a; 42
db $80; 128
db $a2; 162
db $83; 131
db $87; 135
db $53; 83	'S'
db $04; 4
db $aa; 170
db $80; 128
db $91; 145
db $06; 6
db $87; 135
db $57; 87	'W'
db $03; 3
db $22; 34
db $80; 128
db $90; 144
db $2d; 45
db $87; 135
db $00; 0
db $04; 4
db $22; 34
db $80; 128
db $60; 96
db $59; 89	'Y'
db $87; 135
db $00; 0
db $03; 3
db $22; 34
db $80; 128
db $20; 32
db $83; 131
db $87; 135
db $00; 0
db $04; 4
db $20; 32
db $80; 128
db $10; 16
db $06; 6
db $87; 135
db $00; 0
db $03; 3
db $20; 32
db $80; 128
db $10; 16
db $2d; 45
db $87; 135
db $00; 0
db $04; 4
db $02; 2
db $80; 128
db $10; 16
db $59; 89	'Y'
db $87; 135
db $00; 0
db $03; 3
db $02; 2
db $80; 128
db $10; 16
db $83; 131
db $87; 135
db $00; 0