/*

		SFX_enemy_death

		Sound Effect File.
		
		Info:
			Length			:	7
			Priority		:	10
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_enemy_death[] = {
58, // Header
7,
0, 136, 14, 160, 0, 8, 14, 64, 0, 136, 7, 112, 3, 128, 4, 81, 4, 136, 3, 82, 3, 8, 2, 83, 4, 136, 1, 87
};