/*

		SFX_player_transport

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	13
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_player_transport", ROM0
_SFX_player_transport::
db $fd; 253
db $14; 20
db $00; 0
db $aa; 170
db $40; 64
db $3e; 62
db $16; 22
db $84; 132
db $a0; 160
db $00; 0
db $aa; 170
db $40; 64
db $7e; 126
db $b5; 181
db $84; 132
db $40; 64
db $00; 0
db $aa; 170
db $40; 64
db $fe; 254
db $06; 6
db $87; 135
db $70; 112	'p'
db $00; 0
db $aa; 170
db $40; 64
db $74; 116	't'
db $2d; 45
db $87; 135
db $50; 80	'P'
db $00; 0
db $aa; 170
db $80; 128
db $74; 116	't'
db $83; 131
db $87; 135
db $50; 80	'P'
db $00; 0
db $aa; 170
db $80; 128
db $fe; 254
db $16; 22
db $84; 132
db $a0; 160
db $00; 0
db $aa; 170
db $80; 128
db $fc; 252
db $b5; 181
db $84; 132
db $40; 64
db $00; 0
db $a2; 162
db $80; 128
db $74; 116	't'
db $06; 6
db $87; 135
db $51; 81	'Q'
db $00; 0
db $a2; 162
db $40; 64
db $72; 114	'r'
db $2d; 45
db $87; 135
db $52; 82	'R'
db $00; 0
db $2a; 42
db $40; 64
db $71; 113	'q'
db $83; 131
db $87; 135
db $52; 82	'R'
db $00; 0
db $2a; 42
db $40; 64
db $41; 65	'A'
db $16; 22
db $84; 132
db $53; 83	'S'
db $00; 0
db $aa; 170
db $40; 64
db $31; 49	'1'
db $b5; 181
db $84; 132
db $54; 84	'T'
db $00; 0
db $22; 34
db $80; 128
db $20; 32
db $06; 6
db $87; 135
db $00; 0
db $00; 0
db $22; 34
db $80; 128
db $20; 32
db $2d; 45
db $87; 135
db $00; 0
db $00; 0
db $20; 32
db $40; 64
db $10; 16
db $83; 131
db $87; 135
db $00; 0
db $00; 0
db $20; 32
db $40; 64
db $10; 16
db $16; 22
db $84; 132
db $00; 0
db $00; 0
db $20; 32
db $40; 64
db $10; 16
db $b5; 181
db $84; 132
db $00; 0
db $00; 0
db $02; 2
db $40; 64
db $10; 16
db $06; 6
db $87; 135
db $00; 0
db $00; 0
db $02; 2
db $40; 64
db $20; 32
db $2d; 45
db $87; 135
db $00; 0
db $00; 0
db $02; 2
db $40; 64
db $10; 16
db $83; 131
db $87; 135
db $00; 0