/*

		SFX_15

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	15
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_15_h_INCLUDE
#define __SFX_15_h_INCLUDE
#define CBTFX_PLAY_SFX_15 CBTFX_init(&SFX_15[0])
extern const unsigned char SFX_15[];
#endif