/*

		SFX_19

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	13
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_19_h_INCLUDE
#define __SFX_19_h_INCLUDE
#define CBTFX_PLAY_SFX_19 CBTFX_init(&SFX_19[0])
extern const unsigned char SFX_19[];
#endif