/*

		SFX_enemy_fire

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_enemy_fire", ROM0
_SFX_enemy_fire::
db $c0; 192
db $03; 3
db $00; 0
db $22; 34
db $80; 128
db $f0; 240
db $83; 131
db $87; 135
db $00; 0
db $22; 34
db $80; 128
db $a0; 160
db $2d; 45
db $87; 135
db $00; 0
db $22; 34
db $80; 128
db $80; 128
db $06; 6
db $87; 135