/*

		SFX_player_death

		Sound Effect File.
		
		Info:
			Length			:	31
			Priority		:	15
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_player_death", ROM0
_SFX_player_death::
db $ff; 255
db $1f; 31
db $00; 0
db $aa; 170
db $80; 128
db $fa; 250
db $8a; 138
db $87; 135
db $a0; 160
db $01; 1
db $aa; 170
db $80; 128
db $fa; 250
db $2d; 45
db $87; 135
db $80; 128
db $00; 0
db $aa; 170
db $80; 128
db $fa; 250
db $89; 137
db $86; 134
db $40; 64
db $01; 1
db $aa; 170
db $80; 128
db $94; 148
db $89; 137
db $85; 133
db $40; 64
db $00; 0
db $a2; 162
db $80; 128
db $94; 148
db $9b; 155
db $83; 131
db $40; 64
db $01; 1
db $a2; 162
db $80; 128
db $94; 148
db $9c; 156
db $80; 128
db $40; 64
db $00; 0
db $a2; 162
db $80; 128
db $84; 132
db $8a; 138
db $87; 135
db $41; 65	'A'
db $01; 1
db $a2; 162
db $80; 128
db $84; 132
db $2d; 45
db $87; 135
db $41; 65	'A'
db $00; 0
db $2a; 42
db $80; 128
db $84; 132
db $89; 137
db $86; 134
db $41; 65	'A'
db $01; 1
db $2a; 42
db $80; 128
db $73; 115	's'
db $89; 137
db $85; 133
db $42; 66	'B'
db $00; 0
db $2a; 42
db $80; 128
db $73; 115	's'
db $9b; 155
db $83; 131
db $42; 66	'B'
db $01; 1
db $2a; 42
db $80; 128
db $73; 115	's'
db $9c; 156
db $80; 128
db $42; 66	'B'
db $00; 0
db $a2; 162
db $80; 128
db $63; 99	'c'
db $8a; 138
db $87; 135
db $43; 67	'C'
db $01; 1
db $a2; 162
db $80; 128
db $63; 99	'c'
db $2d; 45
db $87; 135
db $43; 67	'C'
db $00; 0
db $a2; 162
db $80; 128
db $63; 99	'c'
db $89; 137
db $86; 134
db $43; 67	'C'
db $01; 1
db $a2; 162
db $80; 128
db $52; 82	'R'
db $89; 137
db $85; 133
db $43; 67	'C'
db $00; 0
db $2a; 42
db $80; 128
db $52; 82	'R'
db $9b; 155
db $83; 131
db $54; 84	'T'
db $01; 1
db $2a; 42
db $80; 128
db $52; 82	'R'
db $9c; 156
db $80; 128
db $54; 84	'T'
db $00; 0
db $2a; 42
db $80; 128
db $42; 66	'B'
db $8a; 138
db $87; 135
db $54; 84	'T'
db $01; 1
db $2a; 42
db $80; 128
db $42; 66	'B'
db $2d; 45
db $87; 135
db $54; 84	'T'
db $00; 0
db $2a; 42
db $80; 128
db $42; 66	'B'
db $89; 137
db $86; 134
db $55; 85	'U'
db $01; 1
db $a2; 162
db $80; 128
db $31; 49	'1'
db $89; 137
db $85; 133
db $55; 85	'U'
db $00; 0
db $a2; 162
db $80; 128
db $31; 49	'1'
db $9b; 155
db $83; 131
db $55; 85	'U'
db $01; 1
db $a2; 162
db $80; 128
db $31; 49	'1'
db $9c; 156
db $80; 128
db $55; 85	'U'
db $00; 0
db $a2; 162
db $80; 128
db $11; 17
db $8a; 138
db $87; 135
db $56; 86	'V'
db $01; 1
db $a2; 162
db $80; 128
db $21; 33
db $2d; 45
db $87; 135
db $56; 86	'V'
db $00; 0
db $aa; 170
db $80; 128
db $21; 33
db $89; 137
db $86; 134
db $56; 86	'V'
db $01; 1
db $aa; 170
db $80; 128
db $11; 17
db $89; 137
db $85; 133
db $56; 86	'V'
db $00; 0
db $aa; 170
db $80; 128
db $11; 17
db $9b; 155
db $83; 131
db $57; 87	'W'
db $01; 1
db $aa; 170
db $80; 128
db $11; 17
db $9c; 156
db $80; 128
db $57; 87	'W'
db $03; 3
db $88; 136
db $00; 0
db $01; 1
db $39; 57	'9'
db $87; 135
db $57; 87	'W'