/*

		SFX_enemy_death

		Sound Effect File.
		
		Info:
			Length			:	7
			Priority		:	10
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_enemy_death", ROM0
_SFX_enemy_death::
db $3a; 58
db $07; 7
db $00; 0
db $88; 136
db $0e; 14
db $a0; 160
db $00; 0
db $08; 8
db $0e; 14
db $40; 64
db $00; 0
db $88; 136
db $07; 7
db $70; 112	'p'
db $03; 3
db $80; 128
db $04; 4
db $51; 81	'Q'
db $04; 4
db $88; 136
db $03; 3
db $52; 82	'R'
db $03; 3
db $08; 8
db $02; 2
db $53; 83	'S'
db $04; 4
db $88; 136
db $01; 1
db $57; 87	'W'