/*

		SFX_enemy_death_special

		Sound Effect File.
		
		Info:
			Length			:	14
			Priority		:	14
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_enemy_death_special[] = {
254, // Header
14,
0, 170, 128, 254, 6, 135, 160, 0, 42, 128, 238, 6, 135, 64, 0, 170, 128, 215, 6, 135, 112, 3, 162, 128, 196, 45, 135, 81, 4, 170, 128, 179, 89, 135, 82, 3, 42, 128, 162, 131, 135, 83, 4, 170, 128, 145, 6, 135, 87, 3, 34, 128, 144, 45, 135, 0, 4, 34, 128, 96, 89, 135, 0, 3, 34, 128, 32, 131, 135, 0, 4, 32, 128, 16, 6, 135, 0, 3, 32, 128, 16, 45, 135, 0, 4, 2, 128, 16, 89, 135, 0, 3, 2, 128, 16, 131, 135, 0
};