/*

		SFX_player_fire

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	1
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_player_fire[] = {
193, // Header
3,
0, 34, 64, 240, 178, 134, 0, 34, 128, 160, 91, 134, 0, 34, 128, 192, 99, 133
};