/*

		SFX_player_transport

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	13
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_player_transport_h_INCLUDE
#define __SFX_player_transport_h_INCLUDE
#define CBTFX_PLAY_SFX_player_transport CBTFX_init(&SFX_player_transport[0])
extern const unsigned char SFX_player_transport[];
#endif