/*

		SFX_player_fire

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	1
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
SECTION "SFX_player_fire", ROM0
_SFX_player_fire::
db $c1; 193
db $03; 3
db $00; 0
db $22; 34
db $40; 64
db $f0; 240
db $b2; 178
db $86; 134
db $00; 0
db $22; 34
db $80; 128
db $a0; 160
db $5b; 91
db $86; 134
db $00; 0
db $22; 34
db $80; 128
db $c0; 192
db $63; 99	'c'
db $85; 133