/*

		SFX_enemy_fire

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_enemy_fire_h_INCLUDE
#define __SFX_enemy_fire_h_INCLUDE
#define CBTFX_PLAY_SFX_enemy_fire CBTFX_init(&SFX_enemy_fire[0])
extern const unsigned char SFX_enemy_fire[];
#endif